mountains=['K2 godwin austin','Nanda','Mahadev','Vindyachal','Arawali','Kanchanjunga']
print(mountains)
mountains.pop()
print(mountains)
mountains.insert(0,'Satpuda')
print(mountains)
mountains.remove('Nanda')
print(mountains)
mountains.append('Nanda')
print(mountains)
print(sorted(mountains))
mountains.reverse()
print(mountains)
print(len(mountains))
